caught exception: "throwing an error string"
